version: '3'

services:
  vpn:
    build: .
    # command: tail -f /dev/null
    image: kgathi2/ipsec-ovpn-server
    restart: always
    env_file:
      - ./vpn.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
      - "1194:1194/udp"
    privileged: true
    volumes:
      - ./volumes/ovpn:/etc/openvpn
      - ./volumes/ipsec:/etc/ipsec.d
